name: CI

on:
  pull_request:
    paths:
      - "**/*.json"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboards repo
        uses: actions/checkout@v5

      - uses: Ana06/get-changed-files@v2.3.0
        id: files
        with:
          format: "json"
          filter: "*.json"

      - name: List added files
        run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<< '${{ steps.files.outputs.added }}')"
          if [ ${#added_files[@]} -eq 0 ]; then
            echo "No added files."
          else
            echo "Added files:"
            for file in "${added_files[@]}"; do
              echo "- $file"
            done
          fi

      - name: List modified files
        run: |
          readarray -t modified_files <<<"$(jq -r '.[]' <<< '${{ steps.files.outputs.modified }}')"
          if [ ${#modified_files[@]} -eq 0 ]; then
            echo "No modified files."
          else
            echo "Modified files:"
            for file in "${modified_files[@]}"; do
              echo "- $file"
            done
          fi

      - name: Generate issue content file
        run: |
          echo "# New JSON Files Added" > issue_content.md
          echo "" >> issue_content.md
          echo "The following JSON files were added in this ${GITHUB_EVENT_NAME}:" >> issue_content.md
          echo "" >> issue_content.md
          readarray -t added_files <<<"$(jq -r '.[]' <<< '${{ steps.files.outputs.added }}')"
          for file in "${added_files[@]}"; do
            echo "- [${file}](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/${file})" >> issue_content.md
          done

      - name: Create issue from file
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "New JSON files added"
          content-filepath: ./issue_content.md
          labels: |
            report
            automated issue
          assignees: crazyuploader
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on the PR with added files
        if: steps.files.outputs.added != '[]' && steps.files.outputs.added != ''
        run: |
          files=$(jq -r '.[]' <<< '${{ steps.files.outputs.added }}')
          comment=":rocket: JSON files added in this PR:\n\n"
          for file in $files; do
            comment+="- [${file}](https://github.com/${{ github.repository }}/blob/${{ github.head_ref }}/${file})\n"
          done
          gh pr comment ${{ github.event.pull_request.number }} --body "$comment"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
