name: CI

on:
  pull_request:
    paths:
      - "**/*.json"
  push:
    paths:
      - "**/*.json"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboards repo
        uses: actions/checkout@v5

      - uses: Ana06/get-changed-files@v2.3.0
        id: files
        with:
          format: "json"
          filter: "*.json"

      - run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<< '${{ steps.files.outputs.added }}')"
          for file in "${added_files[@]}"; do
            echo "File added: $file"
          done
