name: CI

on:
  pull_request:
    paths:
      - "**/*.json"
  push:
    paths:
      - "**/*.json"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboards repo
        uses: actions/checkout@v3

      - uses: Ana06/get-changed-files@v2.3.0
        with:
          format: "json"
          filter: "*.json"

      - name: All
        run: echo ${{steps.files.outputs.all}} | jq

      - name: Added files
        run: echo ${{steps.files.output.added}} | jq
